### PR TITLE
FD-3: Build the server

### PR DESCRIPTION
**Pull request by Hoang-J**
I made the initial server file with the different CRUD endpoints. There are no codes inside each of the endpoints yet. The different npms are included in the package. json file as well.

### CODE REVIEW

**Review by moneymornings — APPROVED** [review]
Looks Good Jessie!

**Review by emartey24 — COMMENTED** [review]
looks great!

**Review by loyaltyjones — APPROVED** [review]
Looks good to me!

**Review by emartey24 — COMMENTED** [review]
Great!

**Pull request merged**
